//LoadingUi
export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";

//Signup
export const SIGNUP_VERIF_MOBILE = "SIGNUP_VERIF_MOBILE";
export const SIGNUP_VERIF_CODESMS = "SIGNUP_VERIF_CODESMS";
export const SIGNUP_MODES_PAYMENT = "SIGNUP_MODES_PAYMENT";
export const SIGNUP_REGISTER_RESPONSE =" SIGNUP_REGISTER_RESPONSE";
