//ui
export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";

export const UI_START_LOADING_BTN = "UI_START_LOADING_BTN";
export const UI_STOP_LOADING_BTN = "UI_STOP_LOADING_BTN";
//Signup
export const SIGNUP_VERIF_MOBILE = "SIGNUP_VERIF_MOBILE";
export const SIGNUP_VERIF_EMPTY = "SIGNUP_VERIF_EMPTY";

export const SIGNUP_VERIF_USEREXIST = "SIGNUP_VERIF_USEREXIST";

export const SINUP_VERIF_CODE = "SINUP_VERIF_CODE";

export const SINUP_GET_MODES_PAYEMENT = "SINUP_GET_MODES_PAYEMENT";

export const SINUP_GET_PRODUCTS = "SINUP_GET_PRODUCTS";

export const SINUP_GET_MODES_COVERY = "SINUP_GET_MODES_COVERY";

export const SIGNUP_REGISTRATION = "SIGNUP_REGISTRATION";

export const EDIT_PROFILE = "EDIT_PROFILE";

export const SINUP_GET_MODES_PAYEMENT_RECOVERY = "SINUP_GET_MODES_PAYEMENT_RECOVERY";

export const AUTHENTIF_TYPE = "AUTHENTIF_TYPE";

export const DATA_AUTHENTIF_TYPE = "DATA_AUTHENTIF_TYPE";

export const SINUP_GET_TYPE_CHOIX_CARD = "SINUP_GET_TYPE_CHOIX_CARD";

export const DATA_SINUP_GET_TYPE_CHOIX_CARD = "DATA_SINUP_GET_TYPE_CHOIX_CARD";

export const DATA_PROFILE_TYPE = "DATA_PROFILE_TYPE";
//Quiz
export const QUIZ_LIST = "QUIZ_LIST";
export const QUIZ_NOTFOUND = "QUIZ_NOTFOUND";
export const QUIZ_QUESTIONS = "QUIZ_QUESTIONS";
export const SCORE = "SCORE";
export const IS_PLAYED = "IS_PLAYED";
export const NB_QUESTIONS = "NB_QUESTIONS";
export const QUESTIONS_IDS = "QUESTIONS_IDS";
export const QUIZ_POINTS = "QUIZ_POINTS";
export const QUIZ_RESPONSES = "QUIZ_RESPONSES";
export const SCORE_QUIZ = "SCORE_QUIZ";
export const NB_RESPONSE = "NB_RESPONSE";

//POINTS
export const HISTORIQUERESULT_TYPE = "HISTORIQUERESULT_TYPE";
export const DATA_HISTORIQUERESULT_TYPE = "DATA_HISTORIQUERESULT_TYPE";

export const PROJECT_RESULT = "PROJECT_RESULT";
export const PROJECT_DATA = "PROJECT_DATA";

export const LIST_CONVERT_POINTS_RESULT_TYPE = "LIST_CONVERT_POINTS_RESULT_TYPE";
export const DATA_LIST_CONVERT_POINTS_TYPE = "DATA_LIST_CONVERT_POINTS_TYPE";

export const PAIEMENT_RESULT_DON = "PAIEMENT_RESULT_DON";
export const PAIEMENT_DATA_DON = "PAIEMENT_DATA_DON";

export const DONRESULT_TYPE = "DONRESULT_TYPE";
export const DATA_DONRESULT_TYPE = "DATA_DONRESULT_TYPE";

//contact
export const RESULT_SEND_CONTACT_TYPE = "RESULT_SEND_CONTACT_TYPE";
export const ERROR_SEND_CONTACT_TYPE = "ERROR_SEND_CONTACT_TYPE";
export const DATA_SEND_CONTACT_TYPE = "DATA_SEND_CONTACT_TYPE";

//partenaires
export const RESULT_PARTENAIRES = "RESULT_PARTENAIRES";
export const DATA_PARTENAIRES = "DATA_PARTENAIRES";

//MEDIA
export const RESULT_GET_ARTICLES_TYPE = "RESULT_GET_ARTICLES_TYPE";
export const DATA_GET_ARTICLES_TYPE = "DATA_GET_ARTICLES_TYPE";



